let chromium;
try{chromium=require('playwright').chromium}
catch{chromium=require(process.env.PLAYWRIGHT_PATH||'/Users/okan/.npm/_npx/e41f203b7505f1fb/node_modules/playwright').chromium}
const fs=require('fs');
const INTENDED=eval(fs.readFileSync(__dirname+'/sim.js','utf8').match(/const INTENDED=(\[[\s\S]*?\]);/)[1]);
let failures=0;
const ok=(name,cond,extra)=>{if(!cond)failures++;console.log(name.padEnd(20)+': '+(cond?'OK':'FAIL')+(extra?' '+extra:''))};
(async()=>{
  fs.mkdirSync(__dirname+'/shots',{recursive:true});
  const br=await chromium.launch({channel:'chrome'}).catch(()=>chromium.launch());
  const pg=await br.newPage({viewport:{width:1060,height:1120}});
  const errors=[],reqs=[];
  pg.on('pageerror',e=>errors.push('PAGEERROR: '+e.message));
  pg.on('console',m=>{if(m.type()==='error')errors.push('CONSOLE: '+m.text())});
  pg.on('request',r=>{if(!r.url().startsWith('file://'))reqs.push(r.url())});
  await pg.goto('file://'+__dirname+'/index.html');
  await pg.waitForTimeout(400);
  await pg.screenshot({path:__dirname+'/shots/00-start.png'});
  ok('start screen',await pg.evaluate(()=>document.getElementById('mapsov').style.display!=='none'&&document.querySelectorAll('#maps button').length===3));
  await pg.click('#maps button:nth-child(1)');
  ok('map select',await pg.evaluate(()=>document.getElementById('mapsov').style.display==='none'&&PLEN===52));

  await pg.locator('#hud').screenshot({path:__dirname+'/shots/60-hud-locked.png'});
  await pg.click('#shop button:nth-child(1)');
  const box=await pg.locator('#cv').boundingBox();
  const cell=(x,y)=>pg.mouse.click(box.x+(x+.5)*box.width/14,box.y+(y+.5)*box.height/9);
  await cell(4,2);
  ok('place via UI',await pg.evaluate(()=>S.towers.length)===1);
  await pg.evaluate(()=>{sel=-1});
  await cell(4,2);
  const info=await pg.locator('#pstats').textContent();
  const nIco=await pg.evaluate(()=>document.querySelectorAll('#pstats img.si').length);
  ok('stats panel',/1\.00\/s/.test(info)&&/2\.5/.test(info)&&nIco>=4,'['+info.trim()+' | icons '+nIco+']');
  await pg.evaluate(()=>{S.gold=2000});
  await pg.click('#panel button:has-text("Upgrade")');
  ok('upgrade via UI',await pg.evaluate(()=>S.towers[0].lvl)===1);
  await pg.evaluate(()=>{const t=S.towers[0];upgrade(S,t);upgrade(S,t);syncPanel()});
  await pg.click('#panel button:has-text("Boulders")');
  ok('branch via UI',await pg.evaluate(()=>S.towers[0].br)===1&&(await pg.locator('#pinfo').textContent()).includes('★Boulders'));
  await pg.evaluate(()=>{place(S,0,5,2);const p=towerAt(S,5,2);upgrade(S,p);upgrade(S,p);upgrade(S,p);branch(S,p,1);syncPanel()});
  await pg.click('#pact .mchip');
  ok('merge via UI',await pg.evaluate(()=>S.towers.length===1&&S.towers[0].lvl===4));
  const st=await pg.locator('#pinfo').textContent()+' | '+await pg.locator('#pstats').textContent();
  ok('L4 stats',st.includes('L4')&&st.includes('★Boulders')&&st.includes('67'),'['+st.trim()+']');
  await pg.evaluate(()=>{S.gold=500;place(S,0,4,0);place(S,0,5,0);place(S,0,6,0);selE=null;selT=towerAt(S,5,0);syncPanel()});
  const mb=await pg.locator('#pact .mchip').count();
  await pg.click('#pact .mchip:has-text("←")');
  ok('merge direction pick',mb===2&&await pg.evaluate(()=>!towerAt(S,4,0)&&towerAt(S,5,0).lvl===1));
  await pg.evaluate(()=>{for(const t of S.towers.filter(t=>t.y===0))sell(S,t);selT=towerAt(S,4,2);syncPanel()});
  await pg.evaluate(()=>{S.wave=15;S.gold=3000;place(S,1,4,4);place(S,3,5,4);
    for(const c of [[4,4],[5,4]]){const t=towerAt(S,c[0],c[1]);upgrade(S,t);upgrade(S,t)}
    selE=null;selT=towerAt(S,4,4);syncPanel()});
  ok('secret offered',(await pg.locator('#pact').textContent()).includes('Meteor Thrower'));
  await pg.click('#pact .mchip');
  ok('secret fused',await pg.evaluate(()=>towerAt(S,4,4).sec===0&&!towerAt(S,5,4))&&(await pg.locator('#pinfo').textContent()).includes('Meteor Thrower'));
  ok('fusion card has no undefined',!(await pg.locator('#panel').textContent()).includes('undefined')&&(await pg.locator('#panel').textContent()).includes('applies burn'));
  await pg.locator('#panel').screenshot({path:__dirname+'/shots/73-secret.png'});
  await pg.evaluate(()=>{sell(S,towerAt(S,4,4));selT=towerAt(S,4,2);syncPanel()});
  await pg.click('#panel button:has-text("Sell")');
  ok('sell via UI',await pg.evaluate(()=>S.towers.length)===0);
  await pg.evaluate(()=>{S.wave=15;S.gold=2000;place(S,0,4,2);place(S,3,5,2)});
  ok('infusion adjacency',await pg.evaluate(()=>towerAt(S,4,2).fire===1));
  await pg.evaluate(()=>{sel=-1});
  await cell(4,2);
  ok('infusion in panel',(await pg.locator('#pstats').textContent()).includes('fire ammo'));
  ok('stasis age-locked',await pg.evaluate(()=>document.getElementById('pws').children[1].disabled));
  await pg.click('#pws button:nth-child(1)');
  await pg.mouse.click(box.x+box.width*.3,box.y+box.height*.45);
  ok('meteor fired',await pg.evaluate(()=>S.pw[0]>0));
  await pg.click('#help');
  const hv=await pg.evaluate(()=>document.getElementById('helpov').style.display);
  await pg.click('#helpov');
  ok('help overlay',hv==='flex'&&await pg.evaluate(()=>document.getElementById('helpov').style.display)==='none');
  await pg.evaluate(()=>{S.wave=10;S.phase='clear'});
  await pg.waitForTimeout(80);
  ok('preview threat hint',(await pg.locator('#nextw').textContent()).includes('armor'));
  await pg.evaluate(()=>{for(const t of S.towers.slice())sell(S,t);S.wave=0;S.gold=80;syncPanel()});
  await pg.click('#spd');
  ok('speed toggle',await pg.evaluate(()=>speed)===3);
  await pg.click('#spd');await pg.click('#mute');await pg.click('#dmgt');
  ok('audio ctx via UI',await pg.evaluate(()=>!!AC));
  ok('wave preview',(await pg.locator('#nextw').textContent()).includes('next: Grunt ×8'));
  await pg.click('#start');
  await pg.evaluate(()=>{for(let k=0;k<80;k++){update(S,1/60);S.ev.length=0}});
  const ep=await pg.evaluate(()=>[S.enemies[0].x,S.enemies[0].y]);
  await pg.mouse.click(box.x+ep[0]*box.width/14,box.y+ep[1]*box.height/9);
  await pg.waitForTimeout(80);
  ok('enemy inspect',(await pg.locator('#pinfo').textContent()).includes('Grunt')&&/\d+\/14/.test(await pg.locator('#pstats').textContent()));
  const g2=await pg.evaluate(()=>Math.floor(S.gold));
  await pg.click('#start');
  ok('early call',await pg.evaluate(g2=>S.wave===2&&Math.floor(S.gold)>g2,g2));
  await pg.evaluate(()=>{S.gold=100;place(S,0,8,2);S.gold=3;selE=null;selT=towerAt(S,8,2);syncPanel()});
  await pg.waitForTimeout(80);
  ok('poor = unclickable',await pg.evaluate(()=>document.querySelector('#panel button[data-c]').disabled));
  ok('card explains upgrade',(await pg.locator('#panel').textContent()).includes('+6%'));
  await pg.evaluate(()=>{S.pick=[0,1,2]});
  await pg.waitForTimeout(120);
  ok('doctrine overlay',await pg.evaluate(()=>document.getElementById('relicov').style.display==='flex'));
  await pg.screenshot({path:__dirname+'/shots/65-doctrine.png'});
  await pg.click('#relics button:nth-child(1)');
  ok('doctrine pick',await pg.evaluate(()=>S.rl.burn7===1&&!S.pick&&document.getElementById('relicov').style.display==='none'));
  await pg.keyboard.press('p');
  const pt0=await pg.evaluate(()=>S.t);
  await pg.waitForTimeout(180);
  ok('pause key',await pg.evaluate(t0=>S.t===t0,pt0));
  await pg.keyboard.press('p');

  await pg.evaluate((build)=>{
    S=mkState();selE=null;selT=null;syncPanel();document.getElementById('end').style.display='none';
    window.__q=build.map(a=>({w:a[0],op:a[1],x:a[2],y:a[3]}));
    window.__tryQ=()=>{const q=__q;while(q.length&&q[0].w<=S.wave-(S.phase==='wave'?1:0)){const a=q[0];let r;
      if(a.op==='u'){const t=towerAt(S,a.x,a.y);r=t&&upgrade(S,t)}
      else if(a.op==='b1'||a.op==='b2'){const t=towerAt(S,a.x,a.y);r=t&&branch(S,t,a.op==='b2'?2:1)}
      else if(a.op==='m'){const t=towerAt(S,a.x,a.y);r=t&&merge(S,t)}
      else if(a.op==='s'){const t=towerAt(S,a.x,a.y);if(t)sell(S,t);r=true}
      else r=place(S,a.op,a.x,a.y);
      if(!r)break;q.shift()}};
    window.__ff=w=>{let g=0;while(!S.over&&(S.wave<w||S.phase==='wave'||S.pick)&&g++<4e6){if(S.pick)pickRelic(S,0);__tryQ();if(S.phase==='clear'&&S.wave<w)startWave(S);update(S,1/30);S.ev.length=0}};
    window.__mid=w=>{__ff(w-1);__tryQ();startWave(S);let g=0;
      while(S.phase==='wave'&&!S.over&&g++<4e6){update(S,1/30);S.ev.length=0;
        if((!S.spawns.length||S.spawns[0].sn>=S.spawns[0].R.n*.6)&&S.enemies.length>3)break}};
  },INTENDED);
  const snaps=[[2,'stone'],[8,'bronze'],[13,'iron'],[18,'medieval'],[23,'gunpowder'],[28,'industrial'],[33,'modern'],[38,'atomic'],[43,'information'],[47,'space']];
  for(const [w,name] of snaps){
    await pg.evaluate(w=>__mid(w),w);
    await pg.waitForTimeout(140);
    await pg.screenshot({path:__dirname+'/shots/'+String(w).padStart(2,'0')+'-'+name+'.png'});
  }
  await pg.evaluate(()=>{selT=towerAt(S,5,6);syncPanel()});
  await pg.waitForTimeout(100);
  await pg.screenshot({path:__dirname+'/shots/48-panel.png'});
  await pg.locator('#hud').screenshot({path:__dirname+'/shots/61-hud-unlocked.png'});
  await pg.locator('#panel').screenshot({path:__dirname+'/shots/62-card.png'});
  await pg.evaluate(()=>{selT=null;syncPanel();__ff(49);__tryQ();startWave(S);for(let k=0;k<420;k++){update(S,1/30);S.ev.length=0}});
  await pg.waitForTimeout(140);
  await pg.screenshot({path:__dirname+'/shots/50-boss.png'});
  const res=await pg.evaluate(()=>{__ff(50);return{won:S.won,lives:S.lives,wave:S.wave}});
  ok('full run in page',res.won&&res.lives>=5,res.won?'VICTORY lives '+res.lives:'died wave '+(res.wave+1));
  await pg.waitForTimeout(200);
  await pg.screenshot({path:__dirname+'/shots/51-victory.png'});
  await pg.click('#endgo');
  await pg.evaluate(()=>__ff(52));
  ok('endless mode',await pg.evaluate(()=>S.endless===1&&S.wave>=51),await pg.evaluate(()=>'reached wave '+S.wave+(S.over?' (died — as designed)':'')));
  await pg.evaluate(()=>{S=mkState();document.getElementById('end').style.display='none';__q.length=0;__ff(50)});
  await pg.waitForTimeout(200);
  await pg.screenshot({path:__dirname+'/shots/52-defeat.png'});
  const d=await pg.evaluate(()=>({over:S.over,won:S.won,txt:document.getElementById('endt').textContent}));
  ok('defeat screen',d.over&&!d.won&&d.txt==='DEFEAT');
  await pg.setViewportSize({width:1280,height:800});
  await pg.waitForTimeout(150);
  ok('fits small viewport',await pg.evaluate(()=>{scrollBy(0,200);return scrollY===0&&document.getElementById('app').getBoundingClientRect().bottom<=innerHeight+2}));
  ok('external requests',reqs.length===0,reqs.join(','));
  console.log(errors.length?'ERRORS:\n'+errors.join('\n'):'page errors         : none');
  failures+=errors.length;
  await br.close();
  if(failures)throw new Error(failures+' browser verification check(s) failed');
})().catch(e=>{console.error(e);process.exit(1)});
